Add gauge chart to score component
cockatoos/cockatoos-app pull request #17
Opened 2021-03-30 21:20 UTC by neshang

We decided to get rid of the analyse dialog in the end and re-design our progress container

In this PR:
1. some styling fixes overall
2. Add gauge chart to the score component

2021-04-01 19:27 UTC, ansonmiu0214 requested changes
Changes look good! Following from the Slack conversation, I'll commit the changes and fix this one as well.

2021-04-01 19:27 UTC, ansonmiu0214 commented on src/app/components/score-chart/score-chart.component.ts
> +                data: [20],
This should be `this.currentValue`

2021-04-02 20:16 UTC, ansonmiu0214 reviewed
Looks great! One last thing - is the gauge fill color supposed to be "squared off" (as shown), or should it cover the circular region?
<img width="246" alt="Screenshot 2021-04-02 at 9 14 56 PM" src="https://user-images.githubusercontent.com/20594247/113450875-af784780-93f8-11eb-96f2-b7770e78a735.png">

2021-04-03 10:50 UTC, neshang commented
@ansonmiu0214 The solid gauge chart shouldn't be cropped out now. Thanks for spotting the bug!

I switched "@media screen and ( max-width: 1700px )" back to 1080px. 1700 seems to be too wide for my laptop..
With the sizes of the charts decreased, it looks good on my laptop now. Let me know if it still looks weird for you.

2021-04-03 12:57 UTC, ansonmiu0214 commented
@neshang 

I get this problem with a 1080px width (Chrome, 100% zoom) - is it different for you?

<img width="1175" alt="Screenshot 2021-04-03 at 1 56 01 PM" src="https://user-images.githubusercontent.com/20594247/113479022-5a821300-9484-11eb-8bc5-aa8083567b66.png">

Chart update LGTM! I also added a y-axis maximum value to cap it at 100.

2021-04-03 14:11 UTC, ansonmiu0214 approved these changes
LGTM! :)

2021-04-03 14:11 UTC, merged